---
# Common variables for all distributions
common_packages:
  - git
  - curl
  - wget
  - htop
  - ripgrep
  - fd
  - make
  - gcc
  - unzip
  - bzip2
  - tree
  - entr
  - xsel

# Development tools
dev_tools:
  # - onedriver 
  # - doctl  # Installed in dev_tools.yml
  # - task  # Installed in dev_tools.yml
  # - lazygit  # Installed in dev_tools.yml
  # - lazydocker  # Installed in dev_tools.yml

