---
# Debian-specific variables
package_manager: apt
package_update_command: apt update
package_install_command: apt install -y
package_remove_command: apt remove -y

# Debian-specific packages
debian_packages:
  - libfuse2 # Required for file system mounting
  - build-essential # Essential development tools
  - libssl-dev # Cryptography library
  - zlib1g-dev # Compression library
  - libbz2-dev # Compression library
  - libsqlite3-dev # SQLite database library
  - libncursesw5-dev # Terminal handling library
