---
# Debian-specific variables
package_manager: apt
package_update_command: apt update
package_install_command: apt install -y
package_remove_command: apt remove -y

# Debian-specific packages
debian_packages:
  - xsel
  - libfuse2
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev 