# Used when testing locally

services:
  caddy:
    ports: !override
      - "8080:80"
      - "8443:443"
    volumes:
      - ./local-sites-enabled:/etc/caddy/sites-enabled
      - ~/github/adventuresoftim/site/:/srv/www/aot
