# Taskfile for webhosting related tasks
# # E.g. created droplet, deploying website, etc.
version: "3"

# NOTE: Cannot use `dotenv` here because this is included in the
#  main taskfile
#
vars:
  GREETING: Hello, World!

includes:
  droplet:
    taskfile: taskfile_droplet.yml
    flatten: false

tasks:
  hello:
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - echo "{{.GREETING}}"
      - echo "Taskfile default dir is {{.TASK_DIR}}"
      - echo "Running from:" {{.USER_WORKING_DIR}}
    silent: true
