---
- name: Install Go using gantsign.golang
  include_role:
    name: gantsign.golang
  vars:
    golang_version: '1.23.4'
    golang_gopath: "{{ ansible_env.HOME }}/go"
    golang_install_dir: "/usr/local/go"

- name: Install golint
  shell: "/usr/local/go/bin/go install golang.org/x/lint/golint@latest"
  args:
    creates: "{{ ansible_env.HOME }}/go/bin/golint"