---
- name: Configure firewall for Debian/Ubuntu
  block:
    - name: Install UFW
      package:
        name: ufw
        state: present
    - name: Install UFW GUI
      package:
        name: gufw
        state: present
    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
        logging: on
    - name: Allow outgoing traffic
      ufw:
        rule: allow
        direction: out
  when: ansible_os_family == 'Debian'

- name: Configure firewall for Archlinux
  block:
    - name: Install and configure firewalld
      package:
        name: firewalld
        state: present
    - name: Enable and start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
  when: ansible_os_family == 'Archlinux' 