---
- name: Install Docker using community.docker role
  ansible.builtin.package:
    name: docker
    state: present

- name: Install Docker Compose
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user | default(ansible_env.USER) }}"
    groups: docker
    append: yes 