---
- name: Install and configure Docker on Archlinux
  block:
    - name: Install Docker and Docker Compose (Arch)
      pacman:
        name:
          - docker
          - docker-compose
        state: present
  when: ansible_os_family == 'Archlinux'

- name: Install and configure Docker on Debian/Ubuntu
  block:
    - name: Install required packages for Docker repo
      apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: yes
    - name: Ensure /etc/apt/keyrings exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Add Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
    - name: Set permissions on Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'
    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture | default('amd64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | default('focal') }} stable"
        state: present
        filename: docker
    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes
    - name: Install Docker packages (latest method)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
  when: ansible_os_family == 'Debian'

- name: Enable and start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group (all platforms)
  user:
    name: "{{ ansible_env.USER | default(ansible_user_id) }}"
    groups: docker
    append: yes

- name: Note about Docker group
  debug:
    msg: "You may need to log out and log back in for docker group membership to take effect." 