---
- name: Install Alacritty
  package:
    name: alacritty
    state: present

- name: Install ZSH and plugins
  package:
    name:
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present

- name: Configure Oh My Zsh using gantsign.oh-my-zsh
  include_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
      - username: "{{ ansible_env.USER | default(ansible_user_id) }}"
        oh_my_zsh:
          theme: robbyrussell
          plugins:
            - aws
            - docker
            - docker-compose
            - doctl
            - dotenv
            - fzf
            - gh
            - git
            - golang
            - npm
            - nvm
            - vi-mode
            - zsh-syntax-highlighting
            - zsh-autosuggestions
            - zsh-history-substring-search
            - zsh-you-should-use
          update_mode: reminder
          update_frequency: 14
          write_zshrc: true

- name: Link plugins.zsh file
  file:
    src: "{{ playbook_dir }}/../config/oh-my-zsh-custom/plugins.zsh"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins.zsh"
    state: link

- name: Link extra.zsh file
  file:
    src: "{{ playbook_dir }}/../config/oh-my-zsh-custom/extra.zsh"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/extra.zsh"
    state: link

- name: Set ZSH as default shell
  shell: chsh -s $(which zsh)
  args:
    executable: /bin/bash 